### ISSUE TITLE
Internet Explorer 11 (Touch) not recognized

### ISSUE THREAD

**Issue by PouleR** [Ikimea/Browser#10]
The following user agent is not correctly parsed as Internet Explorer 11:
"Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko"

See also MSDN: https://msdn.microsoft.com/en-us/library/hh869301(v=vs.85).aspx

**Comment by brniz** [comment]
Hi, you just need to change the line 519 to make room to the keyword 'Touch'.
From:
if (stripos($this->_agent, 'Trident/7.0; rv:11.0') !== false) {

to:
if (stripos($this->_agent, 'Trident/7.0') !== false && stripos($this->_agent, 'rv:11.0') !== false) {

**Comment by Shine-neko** [comment]
@brniz PR ? 👍
