### ISSUE TITLE
Add BackBee project mention 

### ISSUE THREAD

**Issue by mickaelandrieu** [Ikimea/Browser#15]
Hi,

sounds like an update of actual BackBee CMS project class (https://github.com/backbee/BackBee/blob/master/Util/Browser.php).

Would you mind to put a note on this ? It's OK to reuse code, but MIT licence say you have to mention original author.

Regards,

**Comment by Shine-neko** [comment]
Rather http://www.apptools.com/phptools/browser/  
Anyway, it is a forgotten https://github.com/Ikimea/Browser/blob/master/composer.json#L14-L19

**Comment by mickaelandrieu** [comment]
ahahah :) ok, everyone copy but not rely on initial authors ^^, the BackBee class should probably mention Gary White too, but how to know which one was previous author ?

BackBee class was added by the end of 2010, according to the comment in header :/

**Comment by Shine-neko** [comment]
I was not aware of the existence of the project :)
