### ISSUE TITLE
Notice when checking user agent

### ISSUE THREAD

**Issue by rmartignoni** [Ikimea/Browser#21]
Notice: `Undefined offset: 1 .../vendor/ikimea/browser/lib/Ikimea/Browser/Browser.php 660`

User agent: `Dalvik/2.1.0 (Linux; U; Android 8.0.0; ONEPLUS A3010 Build/OPR6.170623.013)`

Line 660: `$aversion = explode(' ', $aresult[1]);`

It seems that some user agents don't have space right after _OPR_ than the notice is logged

**Comment by Shine-neko** [comment]
Why did you close that ?
